//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WTISC._2014.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Livro
    {
        public int ISBN { get; set; }
        public string Titulo { get; set; }
        public string Resumo { get; set; }
        public int IdAutor { get; set; }
        public int IdGenero { get; set; }
        public bool Lido { get; set; }
        public byte[] Capa { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
